<?php
namespace WebBuilder\WebBuilder\Builders;


require_once '/home/joker806/Development/school/DPP/webBuilder/src/WebBuilder/WebBuilder/Builders/SimpleBuilder.php';

/**
 * Test class for SimpleBuilder.
 * Generated by PHPUnit on 2012-03-14 at 22:56:11.
 */
class SimpleBuilderTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var SimpleBuilder
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new SimpleBuilder;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers WebBuilder\WebBuilder\Builders\SimpleBuilder::renderBlock
     * @todo Implement testRenderBlock().
     */
    public function testRenderBlock()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers WebBuilder\WebBuilder\Builders\SimpleBuilder::renderSlot
     * @todo Implement testRenderSlot().
     */
    public function testRenderSlot()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers WebBuilder\WebBuilder\Builders\SimpleBuilder::testBlocks
     * @todo Implement testTestBlocks().
     */
    public function testTestBlocks()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
?>
