<?php
namespace WebBuilder;


require_once '/home/joker806/Development/school/DPP/webBuilder/src/WebBuilder/WebBuilder/BlockInstance.php';

/**
 * Test class for BlockInstance.
 * Generated by PHPUnit on 2012-03-14 at 22:49:21.
 */
class BlockInstanceTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var BlockInstance
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new BlockInstance;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers WebBuilder\BlockInstance::addChild
     * @todo Implement testAddChild().
     */
    public function testAddChild()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers WebBuilder\BlockInstance::__toString
     * @todo Implement test__toString().
     */
    public function test__toString()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers WebBuilder\BlockInstance::__sleep
     * @todo Implement test__sleep().
     */
    public function test__sleep()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
?>
