<?php
namespace ExtAdmin\Response;


require_once '/home/joker806/Development/school/DPP/webBuilder/src/ExtAdmin/Response/Response.php';

/**
 * Test class for Response.
 * Generated by PHPUnit on 2012-03-14 at 23:07:27.
 */
class ResponseTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Response
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new ActionResponse;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers ExtAdmin\Response\Response::encode
     * @todo Implement testEncode().
     */
    public function testEncode()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ExtAdmin\Response\Response::setStatus
     * @todo Implement testSetStatus().
     */
    public function testSetStatus()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ExtAdmin\Response\Response::getHTTPStatus
     * @todo Implement testGetHTTPStatus().
     */
    public function testGetHTTPStatus()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ExtAdmin\Response\Response::setSuccess
     * @todo Implement testSetSuccess().
     */
    public function testSetSuccess()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ExtAdmin\Response\Response::getSuccess
     * @todo Implement testGetSuccess().
     */
    public function testGetSuccess()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ExtAdmin\Response\Response::setMessage
     * @todo Implement testSetMessage().
     */
    public function testSetMessage()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ExtAdmin\Response\Response::setData
     * @todo Implement testSetData().
     */
    public function testSetData()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
?>
